using System.Windows.Forms;

namespace CodeStage_Decrypter
{
	public partial class DecrypterForm
	{
		/// <summary>
		/// <p>Automatically generated by Visual Studio</p>
		/// <p><b>DO NOT MODIFY</b></p>
		/// </summary>
		private void InitializeComponent()
		{
			components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DecrypterForm));
			cryptoKeyBox = new TextBox();
			decencButton = new Button();
			regGroupBox = new GroupBox();
			versionUpDown = new NumericUpDown();
			label4 = new Label();
			getKeyButton = new Button();
			loadButton = new Button();
			progressBar1 = new ProgressBar();
			label2 = new Label();
			label1 = new Label();
			registryPathBox = new TextBox();
			dumpGroupBox = new GroupBox();
			saveDumpButton = new Button();
			openDialogButton1 = new Button();
			textBox1 = new TextBox();
			label3 = new Label();
			dumpSaveDialog = new SaveFileDialog();
			keyViewList = new BrightIdeasSoftware.ObjectListView();
			nameColumn = new BrightIdeasSoftware.OLVColumn();
			valueColumn = new BrightIdeasSoftware.OLVColumn();
			cellContextMenu = new ContextMenuStrip(components);
			createKeyMenuItem = new ToolStripMenuItem();
			intToolStripMenuItem = new ToolStripMenuItem();
			floatToolStripMenuItem = new ToolStripMenuItem();
			stringToolStripMenuItem = new ToolStripMenuItem();
			dumpThisKeyToolStripMenuItem = new ToolStripMenuItem();
			deleteToolStripMenuItem = new ToolStripMenuItem();
			toolStripSeparator1 = new ToolStripSeparator();
			seeDecryptedNameToolStripMenuItem = new ToolStripMenuItem();
			regGroupBox.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)versionUpDown).BeginInit();
			dumpGroupBox.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)keyViewList).BeginInit();
			cellContextMenu.SuspendLayout();
			SuspendLayout();
			// 
			// cryptoKeyBox
			// 
			resources.ApplyResources(cryptoKeyBox, "cryptoKeyBox");
			cryptoKeyBox.Name = "cryptoKeyBox";
			cryptoKeyBox.TextChanged += cryptoKeyBox_TextChanged;
			// 
			// decencButton
			// 
			resources.ApplyResources(decencButton, "decencButton");
			decencButton.Name = "decencButton";
			decencButton.UseVisualStyleBackColor = true;
			decencButton.Click += decencButton_Click;
			// 
			// regGroupBox
			// 
			regGroupBox.Controls.Add(versionUpDown);
			regGroupBox.Controls.Add(label4);
			regGroupBox.Controls.Add(getKeyButton);
			regGroupBox.Controls.Add(loadButton);
			regGroupBox.Controls.Add(progressBar1);
			regGroupBox.Controls.Add(label2);
			regGroupBox.Controls.Add(label1);
			regGroupBox.Controls.Add(decencButton);
			regGroupBox.Controls.Add(registryPathBox);
			regGroupBox.Controls.Add(cryptoKeyBox);
			resources.ApplyResources(regGroupBox, "regGroupBox");
			regGroupBox.Name = "regGroupBox";
			regGroupBox.TabStop = false;
			// 
			// versionUpDown
			// 
			resources.ApplyResources(versionUpDown, "versionUpDown");
			versionUpDown.Maximum = new decimal(new int[] { 4, 0, 0, 0 });
			versionUpDown.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
			versionUpDown.Name = "versionUpDown";
			versionUpDown.Value = new decimal(new int[] { 3, 0, 0, 0 });
			versionUpDown.ValueChanged += versionUpDown_ValueChanged;
			// 
			// label4
			// 
			resources.ApplyResources(label4, "label4");
			label4.Name = "label4";
			// 
			// getKeyButton
			// 
			resources.ApplyResources(getKeyButton, "getKeyButton");
			getKeyButton.Name = "getKeyButton";
			getKeyButton.UseVisualStyleBackColor = true;
			getKeyButton.Click += getKeyButton_Click;
			// 
			// loadButton
			// 
			resources.ApplyResources(loadButton, "loadButton");
			loadButton.Name = "loadButton";
			loadButton.UseVisualStyleBackColor = true;
			loadButton.Click += loadButton_Click;
			// 
			// progressBar1
			// 
			resources.ApplyResources(progressBar1, "progressBar1");
			progressBar1.Name = "progressBar1";
			// 
			// label2
			// 
			resources.ApplyResources(label2, "label2");
			label2.Name = "label2";
			// 
			// label1
			// 
			resources.ApplyResources(label1, "label1");
			label1.Name = "label1";
			// 
			// registryPathBox
			// 
			resources.ApplyResources(registryPathBox, "registryPathBox");
			registryPathBox.Name = "registryPathBox";
			registryPathBox.TextChanged += textBox1_TextChanged;
			// 
			// dumpGroupBox
			// 
			dumpGroupBox.Controls.Add(saveDumpButton);
			dumpGroupBox.Controls.Add(openDialogButton1);
			dumpGroupBox.Controls.Add(textBox1);
			dumpGroupBox.Controls.Add(label3);
			resources.ApplyResources(dumpGroupBox, "dumpGroupBox");
			dumpGroupBox.Name = "dumpGroupBox";
			dumpGroupBox.TabStop = false;
			// 
			// saveDumpButton
			// 
			resources.ApplyResources(saveDumpButton, "saveDumpButton");
			saveDumpButton.Name = "saveDumpButton";
			saveDumpButton.UseVisualStyleBackColor = true;
			saveDumpButton.Click += saveDumpButton_Click;
			// 
			// openDialogButton1
			// 
			resources.ApplyResources(openDialogButton1, "openDialogButton1");
			openDialogButton1.DialogResult = DialogResult.OK;
			openDialogButton1.Name = "openDialogButton1";
			openDialogButton1.UseVisualStyleBackColor = true;
			openDialogButton1.Click += openDialogButton1_Click;
			// 
			// textBox1
			// 
			resources.ApplyResources(textBox1, "textBox1");
			textBox1.Name = "textBox1";
			// 
			// label3
			// 
			resources.ApplyResources(label3, "label3");
			label3.Name = "label3";
			// 
			// dumpSaveDialog
			// 
			dumpSaveDialog.FileName = "dump";
			resources.ApplyResources(dumpSaveDialog, "dumpSaveDialog");
			// 
			// keyViewList
			// 
			keyViewList.CellEditActivation = BrightIdeasSoftware.ObjectListView.CellEditActivateMode.DoubleClick;
			keyViewList.CellEditUseWholeCell = false;
			keyViewList.Columns.AddRange(new ColumnHeader[] { nameColumn, valueColumn });
			keyViewList.GridLines = true;
			keyViewList.HideSelection = false;
			resources.ApplyResources(keyViewList, "keyViewList");
			keyViewList.Name = "keyViewList";
			keyViewList.ShowGroups = false;
			keyViewList.UseCellFormatEvents = true;
			keyViewList.View = View.Details;
			keyViewList.FormatCell += keyViewList_FormatCell;
			keyViewList.KeyUp += keyViewList_KeyUp;
			// 
			// nameColumn
			// 
			nameColumn.AspectName = "Name";
			nameColumn.AutoCompleteEditorMode = AutoCompleteMode.Suggest;
			resources.ApplyResources(nameColumn, "nameColumn");
			// 
			// valueColumn
			// 
			valueColumn.AspectName = "Value";
			valueColumn.AutoCompleteEditor = false;
			valueColumn.AutoCompleteEditorMode = AutoCompleteMode.None;
			valueColumn.IsEditable = false;
			resources.ApplyResources(valueColumn, "valueColumn");
			valueColumn.UseFiltering = false;
			// 
			// cellContextMenu
			// 
			cellContextMenu.Items.AddRange(new ToolStripItem[] { createKeyMenuItem, dumpThisKeyToolStripMenuItem, deleteToolStripMenuItem, toolStripSeparator1, seeDecryptedNameToolStripMenuItem });
			cellContextMenu.Name = "cellContextMenu";
			cellContextMenu.ShowImageMargin = false;
			resources.ApplyResources(cellContextMenu, "cellContextMenu");
			// 
			// createKeyMenuItem
			// 
			createKeyMenuItem.DropDownItems.AddRange(new ToolStripItem[] { intToolStripMenuItem, floatToolStripMenuItem, stringToolStripMenuItem });
			createKeyMenuItem.Name = "createKeyMenuItem";
			resources.ApplyResources(createKeyMenuItem, "createKeyMenuItem");
			// 
			// intToolStripMenuItem
			// 
			intToolStripMenuItem.Name = "intToolStripMenuItem";
			resources.ApplyResources(intToolStripMenuItem, "intToolStripMenuItem");
			intToolStripMenuItem.Click += createKeyToolStripMenuItem_Click;
			// 
			// floatToolStripMenuItem
			// 
			floatToolStripMenuItem.Name = "floatToolStripMenuItem";
			resources.ApplyResources(floatToolStripMenuItem, "floatToolStripMenuItem");
			floatToolStripMenuItem.Click += createKeyToolStripMenuItem_Click;
			// 
			// stringToolStripMenuItem
			// 
			stringToolStripMenuItem.Name = "stringToolStripMenuItem";
			resources.ApplyResources(stringToolStripMenuItem, "stringToolStripMenuItem");
			stringToolStripMenuItem.Click += createKeyToolStripMenuItem_Click;
			// 
			// dumpThisKeyToolStripMenuItem
			// 
			dumpThisKeyToolStripMenuItem.Name = "dumpThisKeyToolStripMenuItem";
			resources.ApplyResources(dumpThisKeyToolStripMenuItem, "dumpThisKeyToolStripMenuItem");
			dumpThisKeyToolStripMenuItem.Click += dumpThisKeyToolStripMenuItem_Click;
			// 
			// deleteToolStripMenuItem
			// 
			deleteToolStripMenuItem.Name = "deleteToolStripMenuItem";
			resources.ApplyResources(deleteToolStripMenuItem, "deleteToolStripMenuItem");
			deleteToolStripMenuItem.Click += deleteToolStripMenuItem_Click;
			// 
			// toolStripSeparator1
			// 
			toolStripSeparator1.Name = "toolStripSeparator1";
			resources.ApplyResources(toolStripSeparator1, "toolStripSeparator1");
			// 
			// seeDecryptedNameToolStripMenuItem
			// 
			seeDecryptedNameToolStripMenuItem.Name = "seeDecryptedNameToolStripMenuItem";
			resources.ApplyResources(seeDecryptedNameToolStripMenuItem, "seeDecryptedNameToolStripMenuItem");
			seeDecryptedNameToolStripMenuItem.Click += seeDecryptedNameToolStripMenuItem_Click;
			// 
			// DecrypterForm
			// 
			resources.ApplyResources(this, "$this");
			AutoScaleMode = AutoScaleMode.Font;
			Controls.Add(keyViewList);
			Controls.Add(dumpGroupBox);
			Controls.Add(regGroupBox);
			FormBorderStyle = FormBorderStyle.FixedSingle;
			MaximizeBox = false;
			Name = "DecrypterForm";
			SizeGripStyle = SizeGripStyle.Hide;
			Activated += DecrypterForm_Activated;
			Deactivate += DecrypterForm_Deactivate;
			FormClosing += DecrypterForm_FormClosing;
			Load += Form1_Load;
			regGroupBox.ResumeLayout(false);
			regGroupBox.PerformLayout();
			((System.ComponentModel.ISupportInitialize)versionUpDown).EndInit();
			dumpGroupBox.ResumeLayout(false);
			dumpGroupBox.PerformLayout();
			((System.ComponentModel.ISupportInitialize)keyViewList).EndInit();
			cellContextMenu.ResumeLayout(false);
			ResumeLayout(false);
		}

		private TextBox cryptoKeyBox;
		private Button decencButton;
		private GroupBox regGroupBox;
		private Label label1;
		private TextBox registryPathBox;
		private Label label2;
		private System.ComponentModel.IContainer components;
		private Button loadButton;
		private ProgressBar progressBar1;
		private Button getKeyButton;
		private GroupBox dumpGroupBox;
		private Label label3;
		private SaveFileDialog dumpSaveDialog;
		private TextBox textBox1;
		private Button openDialogButton1;
		private BrightIdeasSoftware.ObjectListView keyViewList;
		private BrightIdeasSoftware.OLVColumn nameColumn;
		private BrightIdeasSoftware.OLVColumn valueColumn;
		private Button saveDumpButton;
		private Label label4;
		private NumericUpDown versionUpDown;
		private ContextMenuStrip cellContextMenu;
		private ToolStripMenuItem createKeyMenuItem;
		private ToolStripMenuItem dumpThisKeyToolStripMenuItem;
		private ToolStripMenuItem deleteToolStripMenuItem;
		private ToolStripMenuItem intToolStripMenuItem;
		private ToolStripMenuItem floatToolStripMenuItem;
		private ToolStripMenuItem stringToolStripMenuItem;
		private ToolStripSeparator toolStripSeparator1;
		private ToolStripMenuItem seeDecryptedNameToolStripMenuItem;
	}
}